definitions:
  api.ParseErrorType:
    additionalProperties:
      type: string
    type: object
  api.ResponseError:
    properties:
      errors:
        items:
          $ref: '#/definitions/api.ParseErrorType'
        type: array
    type: object
  dto.CreateUserDTO:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
  dto.UpdateUserDTO:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
  user.Model:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      isEmail:
        type: boolean
      name:
        type: string
      patronymic:
        type: string
      surname:
        type: string
      updatedAt:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.Model'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ResponseError'
      summary: Авторизация
      tags:
      - users
  /users/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.Model'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ResponseError'
      summary: Список пользователей
      tags:
      - users
  /users/{user_id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserDTO'
      - description: ID пользователя
        in: path
        name: user_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.Model'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ResponseError'
      summary: Обновить пользователя
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
